# Generated by Django 6.0 on 2026-01-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncapture',
            name='in_team',
        ),
    ]
