# Dictionnaire de traduction des types et couleurs
TYPE_TRANSLATIONS = {
    # Format : "type_anglais": ("Type Français", "nom_couleur_tailwind")
    "normal": ("Normal", "gray"),
    "fire": ("Feu", "red"),
    "water": ("Eau", "blue"),
    "electric": ("Électrik", "yellow"),
    "grass": ("Plante", "green"),
    "ice": ("Glace", "cyan"),
    "fighting": ("Combat", "orange"),
    "poison": ("Poison", "purple"),
    "ground": ("Sol", "amber"),
    "flying": ("Vol", "sky"),
    "psychic": ("Psy", "pink"),
    "bug": ("Insecte", "lime"),
    "rock": ("Roche", "stone"),
    "ghost": ("Spectre", "violet"),
    "dragon": ("Dragon", "indigo"),
    "steel": ("Acier", "slate"),
    "fairy": ("Fée", "rose"),
}
# Dictionnaire de mapping Français -> Anglais
FRENCH_TO_ENGLISH = {
    "bulbizarre": "bulbasaur",
    "herbizarre": "ivysaur",
    "florizarre": "venusaur",
    "salameche": "charmander",
    "reptincel": "charmeleon",
    "dracaufeu": "charizard",
    "carapuce": "squirtle",
    "carabaffe": "wartortle",
    "tortank": "blastoise",
    "chenipan": "caterpie",
    "chrysacier": "metapod",
    "papilusion": "butterfree",
    "aspicot": "weedle",
    "coconfort": "kakuna",
    "dardargnan": "beedrill",
    "roucool": "pidgey",
    "roucoups": "pidgeotto",
    "roucarnage": "pidgeot",
    "rattata": "rattata",
    "rattatac": "raticate",
    "piafabec": "spearow",
    "rapasdepic": "fearow",
    "abo": "ekans",
    "arbok": "arbok",
    "pikachu": "pikachu",
    "raichu": "raichu",
    "sabelette": "sandshrew",
    "sablaireau": "sandslash",
    "nidoran♀": "nidoran-f",
    "nidorina": "nidorina",
    "nidoqueen": "nidoqueen",
    "nidoran♂": "nidoran-m",
    "nidorino": "nidorino",
    "nidoking": "nidoking",
    "melofee": "clefairy",
    "melodelfe": "clefable",
    "goupix": "vulpix",
    "feunard": "ninetales",
    "rondoudou": "jigglypuff",
    "grodoudou": "wigglytuff",
    "nosferapti": "zubat",
    "nosferalto": "golbat",
    "mystherbe": "oddish",
    "ortide": "gloom",
    "rafflesia": "vileplume",
    "paras": "paras",
    "parasect": "parasect",
    "mimitoss": "venonat",
    "aeromite": "venomoth",
    "taupiqueur": "diglett",
    "triopikeur": "dugtrio",
    "miaouss": "meowth",
    "persian": "persian",
    "psykokwak": "psyduck",
    "akwakwak": "golduck",
    "ferosinge": "mankey",
    "colossinge": "primeape",
    "caninos": "growlithe",
    "arcanin": "arcanine",
    "ptitard": "poliwag",
    "tetarte": "poliwhirl",
    "tartard": "poliwrath",
    "abra": "abra",
    "kadabra": "kadabra",
    "alakazam": "alakazam",
    "machoc": "machop",
    "machopeur": "machoke",
    "mackogneur": "machamp",
    "chetiflor": "bellsprout",
    "boustiflor": "weepinbell",
    "empiflor": "victreebel",
    "tentacool": "tentacool",
    "tentacruel": "tentacruel",
    "racaillou": "geodude",
    "gravalanch": "graveler",
    "grolem": "golem",
    "ponyta": "ponyta",
    "galopa": "rapidash",
    "ramoloss": "slowpoke",
    "flagadoss": "slowbro",
    "magneti": "magnemite",
    "magneton": "magneton",
    "canarticho": "farfetchd",
    "doduo": "doduo",
    "dodrio": "dodrio",
    "otaria": "seel",
    "lamantine": "dewgong",
    "tadmorv": "grimer",
    "grotadmorv": "muk",
    "kokiyas": "shellder",
    "crustabri": "cloyster",
    "fantominus": "gastly",
    "spectrum": "haunter",
    "ectoplasma": "gengar",
    "onix": "onix",
    "soporifik": "drowzee",
    "hypnomade": "hypno",
    "krabby": "krabby",
    "krabboss": "kingler",
    "voltorbe": "voltorb",
    "electrode": "electrode",
    "noeunoeuf": "exeggcute",
    "noadkoko": "exeggutor",
    "osselait": "cubone",
    "ossatueur": "marowak",
    "kicklee": "hitmonlee",
    "tygnon": "hitmonchan",
    "excelangue": "lickitung",
    "smogo": "koffing",
    "smogogo": "weezing",
    "rhinocorne": "rhyhorn",
    "rhinoferos": "rhydon",
    "leveinard": "chansey",
    "saquedeneu": "tangela",
    "kangourex": "kangaskhan",
    "hypotrempe": "horsea",
    "hypocean": "seadra",
    "poissirene": "goldeen",
    "poissoroy": "seaking",
    "stari": "staryu",
    "staross": "starmie",
    "m-mime": "mr-mime",
    "insecateur": "scyther",
    "lippoutou": "jynx",
    "elektek": "electabuzz",
    "magmar": "magmar",
    "scarabrute": "pinsir",
    "tauros": "tauros",
    "magicarpe": "magikarp",
    "leviator": "gyarados",
    "lokhlass": "lapras",
    "metamorph": "ditto",
    "evoli": "eevee",
    "aquali": "vaporeon",
    "voltali": "jolteon",
    "pyroli": "flareon",
    "porygon": "porygon",
    "amonita": "omanyte",
    "amonistar": "omastar",
    "kabuto": "kabuto",
    "kabutops": "kabutops",
    "ptera": "aerodactyl",
    "ronflex": "snorlax",
    "artikodin": "articuno",
    "electhor": "zapdos",
    "sulfura": "moltres",
    "minidraco": "dratini",
    "draco": "dragonair",
    "dracolosse": "dragonite",
    "mewtwo": "mewtwo",
    "mew": "mew",
}

# Génération automatique du dictionnaire inverse
ENGLISH_TO_FRENCH = {v: k for k, v in FRENCH_TO_ENGLISH.items()}
